/*
 * search_stub.c — TEMPORARY placeholder for Member 3's search functions.
 *
 * PURPOSE
 *   This file makes the project compile and link before Member 3 delivers
 *   their real search.c.  Every function here is a no-op stub that returns
 *   0 results so the server runs and can be tested end-to-end for ADD,
 *   STATS, and QUIT even without a real search implementation.
 *
 * HOW TO REPLACE
 *   Member 3 should:
 *     1. Create search.c with the real search_brute() implementation.
 *     2. In the Makefile, remove "search_stub.c" and add "search.c"
 *        to the SERVER_SRCS list.
 *     3. Delete (or keep) this file — it is no longer compiled.
 *
 * DO NOT edit this file for real search logic.
 */

#include "vdb_interface.h"

/*
 * search_brute — stub: always returns 0 results and VS_OK.
 *
 * The real implementation (Member 3) must:
 *   • Iterate over all vs->count vectors using vs_get_vector() / vs_get_id().
 *   • Compute the squared Euclidean distance to `query` for each.
 *   • Keep the k smallest distances in a max-heap.
 *   • Fill out_results sorted by distance ascending.
 *   • Set out_results[i].store_index = i (the slot index) so Member 1
 *     can retrieve the vector's float components via vs_get_vector().
 *   • Set *out_count to the actual number of results (may be < k).
 *   • Do NOT call vs_lock() — the caller (command.c) already holds it.
 */
int search_brute(const vector_store_t *vs,
                 const float          *query,
                 int                   k,
                 search_result_t      *out_results,
                 int                  *out_count)
{
    /* suppress unused-parameter warnings */
    (void)vs;
    (void)query;
    (void)k;
    (void)out_results;

    *out_count = 0;   /* stub: no results */
    return VS_OK;
}
